networks:
  web:
    external: true

volumes:
  gitea-data:
  postgres-data:
  harbor-data:

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard Traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/traefik/dynamic_tls.yml"
      - "--providers.file.directory=/traefik"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.http.tls=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.groupe5.com`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certs:/certs:ro
      - ./traefik/dynamic_tls.yml:/traefik/dynamic_tls.yml:ro
      - ./traefik:/traefik:ro


  postgres:
    image: postgres:16
    container_name: gitea-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - web

  gitea:
    image: gitea/gitea
    container_name: gitea
    depends_on:
      - postgres
    ports:
      - "3000:3000"  # Gitea Web UI
      - "222:22"     # Gitea SSH
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: postgres:5432
      GITEA__database__NAME: ${POSTGRES_DB}
      GITEA__database__USER: ${POSTGRES_USER}
      GITEA__database__PASSWD: ${POSTGRES_PASSWORD}
      GITEA__server__ROOT_URL: ${GITEA_ROOT_URL}
      GITEA__server__DOMAIN: ${GITEA_DOMAIN}
      GITEA__server__SSH_DOMAIN: ${GITEA_SSH_DOMAIN}
      GITEA__server__PROTOCOL: ${GITEA_PROTOCOL}
      GITEA__server__HTTP_PORT: ${GITEA_HTTP_PORT}
      GITEA__server__SSH_PORT: ${GITEA_SSH_PORT}
    volumes:
      - gitea-data:/data
    # labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.gitea.rule=Host(`git.groupe5.com`)"
      # - "traefik.http.routers.gitea.entrypoints=websecure"
      # - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      # - "traefik.http.middlewares.gitea-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      # - "traefik.http.middlewares.gitea-headers.headers.customrequestheaders.X-Forwarded-Host=git.groupe5.com"
      # - "traefik.http.routers.gitea.middlewares=gitea-headers"
    networks:
      - web
    restart: always

  runner:
    image: gitea/act_runner:latest
    container_name: gitea-runner
    depends_on:
      - gitea
    environment:
      # CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: ${GITEA_INSTANCE_URL}
      GITEA_RUNNER_REGISTRATION_TOKEN: ${GITEA_RUNNER_REGISTRATION_TOKEN}
      GITEA_RUNNER_NAME: ${GITEA_RUNNER_NAME}
    volumes:
      # - ./config.yaml:/config.yaml
      - ./runner-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    restart: always

  # registry:
  #   image: registry:2
  #   container_name: registry
  #   restart: always
  #   # ports:
  #   #   - "5000:5000"
  #   environment:
  #     - REGISTRY_HTTP_SECRET=ivan-2003Kk
  #   volumes:
  #     - ./registry-data:/var/lib/registry
  #   networks:
  #     - web
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.registry.rule=Host(`registry.groupe5.com`)"
  #     - "traefik.http.routers.registry.entrypoints=websecure"
  #     - "traefik.http.services.registry.loadbalancer.server.port=5000"
  #     - "traefik.http.middlewares.registry-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
  #     - "traefik.http.middlewares.registry-headers.headers.customrequestheaders.X-Forwarded-Host=registry.groupe5.com"
  #     - "traefik.http.routers.registry.middlewares=registry-headers"
